# Generated by Django 5.1.7 on 2025-03-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passports", "0002_bordercrossingapplication_delete_bordercrossing"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("link", models.URLField()),
                ("date_published", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "ordering": ["-date_published"],
            },
        ),
    ]
